### ISSUE TITLE
Please add Toad and Rayman in a unique download without Ult S.

### ISSUE THREAD

**Issue by SwitchAdventurer** [chrispo-git/ult-s#350]
Hi Chrispo, I wanted to ask you something: could you please add Toad and Rayman in a single download without the support of Ultimate S. I tried to do it myself but I couldn't, so only you can do it. Please, I would like to play them individually with other mods. If you can, please publish it to your release site on this github downloads. Thank you and good day

**Comment by Gazoon007** [comment]
> Hi Chrispo, I wanted to ask you something: could you please add Toad and Rayman in a single download without the support of Ultimate S. I tried to do it myself but I couldn't, so only you can do it. Please, I would like to play them individually with other mods. If you can, please publish it to your release site on this github downloads. Thank you and good day

He's working so hard on the Ultimate S, so the only way you can pay for his effort is by playing in Ultimate S. He won't grant your request anyway.
