### ISSUE TITLE
Platforms on Kongo Falls are invisible

### ISSUE THREAD

**Issue by Scepty-SSB** [chrispo-git/ult-s#453]
The platforms on the Kongo Falls stage are invisible (at least for me.) They still function perfectly fine, but the stage is visually identical to the Omega version from the base game.
![invis-kongo-falls](https://github.com/chrispo-git/ult-s/assets/168497715/483dcb44-143e-437b-84e2-eeb79966aa6c)

**Comment by sentinelofinfect** [comment]
try turning hazards on, that tends to solve this issue

**Comment by Scepty-SSB** [comment]
That fixed it, thank you!
