### ISSUE TITLE
question about the mods

### ISSUE THREAD

**Issue by adlia06** [chrispo-git/ult-s#454]
Hello, do you think that custum characters would ever have a separated download from the modpack, or would they be tied to the modpack? i really want to be able to play the toad mod but i dont want the moveset changes as me and my friends are used to the original movesets. i know it would require lots of work to separate each mods so i understand if it's not possible.

**Comment by mRama3415** [comment]
this is not an issue, and is not what this github feature is meant for. u need to play ultimate S to play with all of its features, including custom characters.
